name: DEPLOY
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: .
        remote_path: /srv/deploy/get-checkmated
        remote_host: 65.108.80.178
        remote_user: deploy
        remote_key: ${{ secrets.DEPLOY_KEY }}
