name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "."
          REMOTE_HOST: "65.108.80.178"
          REMOTE_USER: "deploy"
          TARGET: "/srv/deploy/get-checkmated/releases/${{ github.sha }}"
          SCRIPT_BEFORE: |
            whoami
            ls -al
            env
            echo $GITHUB_SHA
          SCRIPT_AFTER: |
            whoami
            ls -al
          
